### ISSUE TITLE
Webhook errors even if message was sent.

### ISSUE THREAD

**Issue by EasternBloxxer** [regginator/s3forcer#1]
Would make a pr to fix this but i have basically no python knowledge so i will not.
![image](https://user-images.githubusercontent.com/54174182/234808881-6ef66494-ae94-4d17-ab4b-a45cb7021119.png)

**Comment by regginator** [comment]
Oh I made a change yesterday that's probably causing that message; but that isn't actually an error lol. I'll change that back rq
